name: py310
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.6=hb03c661_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cmake=3.14.0=hf94ab9c_0
  - curl=8.8.0=he654da7_1
  - expat=2.7.3=hecca717_0
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.45=bootstrap_ha15bf96_5
  - libcurl=8.8.0=hca28451_1
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=he0feb66_16
  - libgcc-ng=15.2.0=h69a702a_16
  - libgomp=15.2.0=he0feb66_16
  - liblzma=5.8.2=hb03c661_0
  - liblzma-devel=5.8.2=hb03c661_0
  - libnghttp2=1.58.0=h47da74e_1
  - libnsl=2.0.1=hb9d3cd8_1
  - libsqlite=3.46.0=hde9e2c9_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx=15.2.0=h934c35e_16
  - libstdcxx-ng=15.2.0=hdf11a46_16
  - libuuid=2.41.3=h5347b49_0
  - libuv=1.51.0=hb03c661_1
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.2.13=h4ab18f5_6
  - ncurses=6.5=h2d0b736_3
  - openssl=3.6.0=h26f9b46_0
  - packaging=26.0=pyhcf101f3_0
  - pip=25.3=pyh8b19718_0
  - python=3.10.14=hd12c33a_0_cpython
  - readline=8.3=h853b02a_0
  - rhash=1.4.3=hd590300_2
  - setuptools=80.10.1=pyh332efcf_0
  - tk=8.6.13=noxft_h4845f30_101
  - tzdata=2025c=hc9c84f9_1
  - wheel=0.46.3=pyhd8ed1ab_0
  - xz=5.8.2=ha02ee65_0
  - xz-gpl-tools=5.8.2=ha02ee65_0
  - xz-tools=5.8.2=hb03c661_0
  - zlib=1.2.13=h4ab18f5_6
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - absl-py==2.4.0
      - antlr4-python3-runtime==4.9.3
      - attrs==25.4.0
      - black==26.1.0
      - braceexpand==0.1.7
      - certifi==2022.12.7
      - charset-normalizer==2.1.1
      - click==8.3.1
      - cloudpickle==3.1.2
      - contourpy==1.3.2
      - cycler==0.12.1
      - exceptiongroup==1.3.1
      - fonttools==4.61.1
      - gitdb==4.0.12
      - gitpython==3.1.46
      - grpcio==1.76.0
      - gym==0.23.0
      - gym-notices==0.1.0
      - habitat-lab==0.3.2
      - habitat-sim==0.3.2
      - hydra-core==1.3.2
      - idna==3.4
      - ifcfg==0.24
      - imageio==2.37.2
      - imageio-ffmpeg==0.6.0
      - iniconfig==2.3.0
      - isort==7.0.0
      - kiwisolver==1.4.9
      - llvmlite==0.46.0
      - lmdb==1.7.5
      - magnum==0.0.0
      - markdown==3.10.1
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - mypy-extensions==1.1.0
      - numba==0.63.1
      - numpy==1.26.4
      - numpy-quaternion==2024.0.13
      - omegaconf==2.3.0
      - opencv-python==4.10.0.84
      - pathspec==1.0.4
      - pillow==10.4.0
      - platformdirs==4.5.1
      - pluggy==1.6.0
      - protobuf==6.33.5
      - pygments==2.19.2
      - pyparsing==3.3.2
      - pytest==9.0.2
      - python-dateutil==2.9.0.post0
      - pytokens==0.4.1
      - pyyaml==6.0.3
      - requests==2.28.1
      - scipy==1.15.3
      - six==1.17.0
      - smmap==5.0.2
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tomli==2.4.0
      - torch==1.13.1+cu117
      - torchaudio==0.13.1+cu117
      - torchvision==0.14.1+cu117
      - tqdm==4.67.1
      - typing-extensions==4.15.0
      - urllib3==1.26.13
      - webdataset==0.1.103
      - werkzeug==3.1.5
      - yacs==0.1.8
prefix: /data1/user2025263063/miniconda3/envs/py310
