# @package _global_

defaults:
  - pointnav_base
  - /habitat/dataset/pointnav: gibson
  - _self_

habitat:
  environment:
    max_episode_steps: 500

  simulator:
    forward_step_size: 0.25
    turn_angle: 30
    agents:
      main_agent:
        sensors:
          rgb_sensor:
            type: HabitatSimRGBSensor
            width: 256
            height: 256
            position: [0, 1.5, 0]
          depth_sensor:
            type: HabitatSimDepthSensor
            width: 256
            height: 256
            position: [0, 1.5, 0]
            min_depth: 0.1
            max_depth: 5.0

  task:
    measurements:
      collisions:
        type: Collisions
