# @package _global_

defaults:
  - pointnav_base
  - /habitat/dataset/pointnav: gibson
  - _self_

habitat:
  environment:
    max_episode_steps: 500
  simulator:
    should_setup_semantic_ids: false
    scene_dataset: default
    scene: Adrian.glb
    agents:
      main_agent:
        sim_sensors:
          rgb_sensor:
            width: 256
            height: 256
          depth_sensor:
            width: 256
            height: 256
  dataset:
    scenes_dir: /data2/wukaitong/gibson/data/scene_datasets
    data_path: /data1/user2025263063/project/MARLObjectNav/envs/habitat/habitat-lab/data/datasets/pointnav/gibson/v1/train/train.json.gz
